# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 3c2c365503e14d84fe8bc37ee81adbe326eb1bcc

{
  "title": "Детские коляски",
  "description": "много старых",
  "created_at": "2019-09-30T07:32:52.047354+02:00"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token 3c2c365503e14d84fe8bc37ee81adbe326eb1bcc

{
  "status": "CLOSED"
}

###

# удалить обьявление
DELETE {{baseUrl}}/advertisements/4/
Authorization: Token 25c86552d5c5bc1be56e6fd7b10e5f701b2f308f


###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-09-30
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json